spring:
  zipkin:
    base-url: http://localhost:9411
    service:
      name: spring-zipkin-metrics
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
